/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployerTimesheetsRouteImport } from './routes/employer.timesheets'
import { Route as EmployerReportsRouteImport } from './routes/employer.reports'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as EmployerCandidatesRouteImport } from './routes/employer.candidates'
import { Route as EmployeeTimesheetsRouteImport } from './routes/employee.timesheets'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeLeaveRouteImport } from './routes/employee.leave'
import { Route as EmployeeDocumentsRouteImport } from './routes/employee.documents'
import { Route as ClientTimesheetsRouteImport } from './routes/client.timesheets'
import { Route as ClientResourcesRouteImport } from './routes/client.resources'
import { Route as ClientRequirementsRouteImport } from './routes/client.requirements'
import { Route as ClientInvoicesRouteImport } from './routes/client.invoices'
import { Route as AdminTimesheetsRouteImport } from './routes/admin.timesheets'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLeaveRouteImport } from './routes/admin.leave'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminTimesheetsIdRouteImport } from './routes/admin.timesheets.$id'
import { Route as AdminLeaveIdRouteImport } from './routes/admin.leave.$id'
import { Route as AdminEmployeesIdRouteImport } from './routes/admin.employees.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployerTimesheetsRoute = EmployerTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerReportsRoute = EmployerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => EmployerRoute,
} as any)
const EmployeeTimesheetsRoute = EmployeeTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeaveRoute = EmployeeLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDocumentsRoute = EmployeeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EmployeeRoute,
} as any)
const ClientTimesheetsRoute = ClientTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => ClientRoute,
} as any)
const ClientResourcesRoute = ClientResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ClientRoute,
} as any)
const ClientRequirementsRoute = ClientRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => ClientRoute,
} as any)
const ClientInvoicesRoute = ClientInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ClientRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaveRoute = AdminLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimesheetsIdRoute = AdminTimesheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTimesheetsRoute,
} as any)
const AdminLeaveIdRoute = AdminLeaveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLeaveRoute,
} as any)
const AdminEmployeesIdRoute = AdminEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEmployeesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/services': typeof ServicesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/leave': typeof AdminLeaveRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/timesheets': typeof AdminTimesheetsRouteWithChildren
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/requirements': typeof ClientRequirementsRoute
  '/client/resources': typeof ClientResourcesRoute
  '/client/timesheets': typeof ClientTimesheetsRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/timesheets': typeof EmployeeTimesheetsRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/employer/reports': typeof EmployerReportsRoute
  '/employer/timesheets': typeof EmployerTimesheetsRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/leave/$id': typeof AdminLeaveIdRoute
  '/admin/timesheets/$id': typeof AdminTimesheetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/services': typeof ServicesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/leave': typeof AdminLeaveRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/timesheets': typeof AdminTimesheetsRouteWithChildren
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/requirements': typeof ClientRequirementsRoute
  '/client/resources': typeof ClientResourcesRoute
  '/client/timesheets': typeof ClientTimesheetsRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/timesheets': typeof EmployeeTimesheetsRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/employer/reports': typeof EmployerReportsRoute
  '/employer/timesheets': typeof EmployerTimesheetsRoute
  '/employee': typeof EmployeeIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/leave/$id': typeof AdminLeaveIdRoute
  '/admin/timesheets/$id': typeof AdminTimesheetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/employer': typeof EmployerRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/services': typeof ServicesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/leave': typeof AdminLeaveRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/timesheets': typeof AdminTimesheetsRouteWithChildren
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/requirements': typeof ClientRequirementsRoute
  '/client/resources': typeof ClientResourcesRoute
  '/client/timesheets': typeof ClientTimesheetsRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/timesheets': typeof EmployeeTimesheetsRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/employer/reports': typeof EmployerReportsRoute
  '/employer/timesheets': typeof EmployerTimesheetsRoute
  '/employee/': typeof EmployeeIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/leave/$id': typeof AdminLeaveIdRoute
  '/admin/timesheets/$id': typeof AdminTimesheetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/client'
    | '/contact'
    | '/employee'
    | '/employer'
    | '/login'
    | '/notifications'
    | '/services'
    | '/admin/activity'
    | '/admin/employees'
    | '/admin/jobs'
    | '/admin/leave'
    | '/admin/reports'
    | '/admin/timesheets'
    | '/client/invoices'
    | '/client/requirements'
    | '/client/resources'
    | '/client/timesheets'
    | '/employee/documents'
    | '/employee/leave'
    | '/employee/profile'
    | '/employee/timesheets'
    | '/employer/candidates'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/timesheets'
    | '/employee/'
    | '/admin/employees/$id'
    | '/admin/leave/$id'
    | '/admin/timesheets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/client'
    | '/contact'
    | '/employer'
    | '/login'
    | '/notifications'
    | '/services'
    | '/admin/activity'
    | '/admin/employees'
    | '/admin/jobs'
    | '/admin/leave'
    | '/admin/reports'
    | '/admin/timesheets'
    | '/client/invoices'
    | '/client/requirements'
    | '/client/resources'
    | '/client/timesheets'
    | '/employee/documents'
    | '/employee/leave'
    | '/employee/profile'
    | '/employee/timesheets'
    | '/employer/candidates'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/timesheets'
    | '/employee'
    | '/admin/employees/$id'
    | '/admin/leave/$id'
    | '/admin/timesheets/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/client'
    | '/contact'
    | '/employee'
    | '/employer'
    | '/login'
    | '/notifications'
    | '/services'
    | '/admin/activity'
    | '/admin/employees'
    | '/admin/jobs'
    | '/admin/leave'
    | '/admin/reports'
    | '/admin/timesheets'
    | '/client/invoices'
    | '/client/requirements'
    | '/client/resources'
    | '/client/timesheets'
    | '/employee/documents'
    | '/employee/leave'
    | '/employee/profile'
    | '/employee/timesheets'
    | '/employer/candidates'
    | '/employer/jobs'
    | '/employer/reports'
    | '/employer/timesheets'
    | '/employee/'
    | '/admin/employees/$id'
    | '/admin/leave/$id'
    | '/admin/timesheets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  EmployerRoute: typeof EmployerRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employer/timesheets': {
      id: '/employer/timesheets'
      path: '/timesheets'
      fullPath: '/employer/timesheets'
      preLoaderRoute: typeof EmployerTimesheetsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/reports': {
      id: '/employer/reports'
      path: '/reports'
      fullPath: '/employer/reports'
      preLoaderRoute: typeof EmployerReportsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof EmployerRoute
    }
    '/employee/timesheets': {
      id: '/employee/timesheets'
      path: '/timesheets'
      fullPath: '/employee/timesheets'
      preLoaderRoute: typeof EmployeeTimesheetsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leave': {
      id: '/employee/leave'
      path: '/leave'
      fullPath: '/employee/leave'
      preLoaderRoute: typeof EmployeeLeaveRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/documents': {
      id: '/employee/documents'
      path: '/documents'
      fullPath: '/employee/documents'
      preLoaderRoute: typeof EmployeeDocumentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/client/timesheets': {
      id: '/client/timesheets'
      path: '/timesheets'
      fullPath: '/client/timesheets'
      preLoaderRoute: typeof ClientTimesheetsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/resources': {
      id: '/client/resources'
      path: '/resources'
      fullPath: '/client/resources'
      preLoaderRoute: typeof ClientResourcesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/requirements': {
      id: '/client/requirements'
      path: '/requirements'
      fullPath: '/client/requirements'
      preLoaderRoute: typeof ClientRequirementsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/invoices': {
      id: '/client/invoices'
      path: '/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof ClientInvoicesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leave': {
      id: '/admin/leave'
      path: '/leave'
      fullPath: '/admin/leave'
      preLoaderRoute: typeof AdminLeaveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timesheets/$id': {
      id: '/admin/timesheets/$id'
      path: '/$id'
      fullPath: '/admin/timesheets/$id'
      preLoaderRoute: typeof AdminTimesheetsIdRouteImport
      parentRoute: typeof AdminTimesheetsRoute
    }
    '/admin/leave/$id': {
      id: '/admin/leave/$id'
      path: '/$id'
      fullPath: '/admin/leave/$id'
      preLoaderRoute: typeof AdminLeaveIdRouteImport
      parentRoute: typeof AdminLeaveRoute
    }
    '/admin/employees/$id': {
      id: '/admin/employees/$id'
      path: '/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AdminEmployeesIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
  }
}

interface AdminEmployeesRouteChildren {
  AdminEmployeesIdRoute: typeof AdminEmployeesIdRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesIdRoute: AdminEmployeesIdRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminLeaveRouteChildren {
  AdminLeaveIdRoute: typeof AdminLeaveIdRoute
}

const AdminLeaveRouteChildren: AdminLeaveRouteChildren = {
  AdminLeaveIdRoute: AdminLeaveIdRoute,
}

const AdminLeaveRouteWithChildren = AdminLeaveRoute._addFileChildren(
  AdminLeaveRouteChildren,
)

interface AdminTimesheetsRouteChildren {
  AdminTimesheetsIdRoute: typeof AdminTimesheetsIdRoute
}

const AdminTimesheetsRouteChildren: AdminTimesheetsRouteChildren = {
  AdminTimesheetsIdRoute: AdminTimesheetsIdRoute,
}

const AdminTimesheetsRouteWithChildren = AdminTimesheetsRoute._addFileChildren(
  AdminTimesheetsRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLeaveRoute: typeof AdminLeaveRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminJobsRoute: AdminJobsRoute,
  AdminLeaveRoute: AdminLeaveRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminTimesheetsRoute: AdminTimesheetsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientInvoicesRoute: typeof ClientInvoicesRoute
  ClientRequirementsRoute: typeof ClientRequirementsRoute
  ClientResourcesRoute: typeof ClientResourcesRoute
  ClientTimesheetsRoute: typeof ClientTimesheetsRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientInvoicesRoute: ClientInvoicesRoute,
  ClientRequirementsRoute: ClientRequirementsRoute,
  ClientResourcesRoute: ClientResourcesRoute,
  ClientTimesheetsRoute: ClientTimesheetsRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface EmployeeRouteChildren {
  EmployeeDocumentsRoute: typeof EmployeeDocumentsRoute
  EmployeeLeaveRoute: typeof EmployeeLeaveRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeTimesheetsRoute: typeof EmployeeTimesheetsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeDocumentsRoute: EmployeeDocumentsRoute,
  EmployeeLeaveRoute: EmployeeLeaveRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeTimesheetsRoute: EmployeeTimesheetsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface EmployerRouteChildren {
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  EmployerReportsRoute: typeof EmployerReportsRoute
  EmployerTimesheetsRoute: typeof EmployerTimesheetsRoute
}

const EmployerRouteChildren: EmployerRouteChildren = {
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  EmployerReportsRoute: EmployerReportsRoute,
  EmployerTimesheetsRoute: EmployerTimesheetsRoute,
}

const EmployerRouteWithChildren = EmployerRoute._addFileChildren(
  EmployerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  EmployerRoute: EmployerRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
